### PR TITLE
[License-Check-Workflow] Add licensecheck workflow for dash itself

### PR DESCRIPTION
**Pull request by HannesWell**
@waynebeaton what do you think about adding this?
To make this fully operational we would have to request an EF Gitlab API token, like in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1454.

### CODE REVIEW

**Comment by waynebeaton** [comment]
I like the idea conceptually. If it works, let's do it.

**Comment by HannesWell** [comment]
> I like the idea conceptually. If it works, let's do it.

Great, then lets have this.
Created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4822 to ask the infra team for a API token so that we can request reviews here too.
But this can already be submitted now, since we only need the token when requesting reviews.

**Pull request merged**
